$(`<img src="https://iraqya.com/sico/z1f0e7nb0210.jpeg" style="width:100%;margin-top: 0px" ><center><div id="asim13"><a id="asim21" href="About-Us.html" style="height: 24px;text-align: center;width:124px;color: #B4B6B8;border-radius: 15px 0px 0px 0px; border-left: 0px solid#f7d322; border-right: 1px solid#ffffff;" class="fl mini fa fa-coffee btn btn-primary"/a><a id="asim21" href="style2.html" style="height: 24px;text-align: center;width:70px;color: #B4B6B8;border-radius: 0px 0 0 0; border-left: 0px solid#f7d322; border-right: 1px solid#ffffff;" class="fl mini fa fa-tencent-weibo btn btn-primary" target="_blank"></a><a id="asim21" href="Contact-Us.html"  style="height: 24px;text-align: center;width:70px;color: #B4B6B8;border-radius: 0px 0 0 0; border-left: 0px solid#f7d322; border-right: 1px solid#ffffff;" class="fl mini fa fa-exclamation-triangle btn-primary" target="_blank"></a></a><a id="asim21" href="" style="height: 24px;text-align: center;width:124px;color: #B4B6B8;border-radius: 0px 15px 0px 0px; border-left: 0px solid#f7d322; border-right: 1px solid#ffffff;" class="fl mini fa fa-envelope btn btn-primary" target="_blank"></a></a></div></div><center>`).insertBefore(".nav-tabs"),$(`<div><marquee direction="right"id="as43"scrollamount="3"> كُل عآم وانتم بِخير ❤️ </marquee><div>`).insertBefore("div#tlogins .lonline.light.break");$(".hand.nosel.fl.uzr.border").css({margin:"1px 0",borderRadius:"0px"}),$(".checkbox label").html(`<input id="stealth" type="checkbox" value=""><i class="fa fa-eye-slash" aria-hidden="true"></i>`),$(".nav-tabs").addClass("fl").css("width","100%"),$("div#tlogins input").attr("maxlength",12),$("textarea#tbox.fl.corner.tbox.filw").attr("maxlength",100),
$(`<link rel="stylesheet" href="https://iraqiachats.com/IQ/i2.css"><style> div#asim13 {
    background: #fff0;
}
ul.nav.nav-tabs>li>.fa-user-plus:before,ul.nav.nav-tabs>li>.fa-user:before,ul.nav.nav-tabs>li>.fa-user:before{color:#d46954}a#asim21,div#tlogins button.btn.btn-primary,label.label.label-primary.mini.fl{background-color:#101c24!important}ul.nav.nav-tabs>li>a{background-color:#101c24}ul.nav.nav-tabs>li.active>a{background-color:#101c24}.fr.borderg{background-color:#101c24!important}.loginstat{background-color:#101c24}label.fl.nosel.label.pnhead{background-color:#101c24}
</style>`).insertBefore("body");
$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),$("#d0").append(`<label title="اذاعة شات مقهى عراقنا"href="#"onclick="$('.pnhead').text($(this).attr('title'));hl($(this),'primary');setTimeout(function(){$('#mic').scrollTop(0);},0);$('.dpnl').show();"data-toggle="tab" data-target="#mic" class="ae fa label label-primary "><i class="fa fa-volume-up" aria-hidden="true"></i></label>`);
$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),$("div#tlogins button.btn.btn-primary").click(function(){var a=setInterval(function(){var b=$(".pmsgc").length;0<b?($(`<iframe id="asim29" src="https://mixlr.com/users/8977615/embed?color=4C5459&amp;artwork=false" frameborder="no"></iframe><a rel="nofollow" title="" href="https://grv.to/iqr30" target="_blank" class="fl mini fa fa-microphone btn btnn-default" style="width: 99%;">الاريل واگع /صيانه</a><a class="fl mini fa fa-bullhorn btn label-primary">اسم البرنامج</a><input type="asim" name="FirstName" value="gruveo"></div><center>`).appendTo("#mic"),clearInterval(a)):console.log(b)},1)}),$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),setInterval(function(){var b=$("#dpnl");0<b.length&&b.remove()},0),$(".dpnl").append(` <div id="mic" style="height: 100%;width:100%;" class="break light tab-pane border"><center></div><center></div>`);
$("button.btn.btn-primary" ).css( "border-radius", "24px 24px 24px 30px" )
$(".label-primary").css("border-radius","0px 50px 30px 40px")
$(document.getElementById("tbox").placeholder = "  المحادثة العامة ");
$("[data-target=#wall]").attr('title',' فضلاً وليس امراً عدم ألكلام في ألحائط')
$("[data-target=#settings]").attr('title','حبشكلات')
$("[data-target=#rooms]").attr('title','ألغرف')
$("[data-target=#chats]").attr('title','لأهل السطوح')
$("[data-target=#users]").attr('title','جماعتك هنا تلكاهم')
